meta_learner: hslapknn
vectors: bert
num_shots:
  wsd: 8
num_updates: 5
num_test_samples:
  wsd: 8
num_train_episodes:
  wsd: 0
num_val_episodes:
  wsd: 167
num_test_episodes:
  wsd: 264
device: cuda:0
write_directory: hslapknn_data/bert_8
