meta_learner: hslapknn
vectors: bert
num_shots:
  wsd: 32
num_test_samples:
  wsd: 32
num_train_episodes:
  wsd: 0
num_val_episodes:
  wsd: 84
num_test_episodes:
  wsd: 129
device: cuda:0
write_directory: hslapknn_data/bert_32
